add expedition to pallete
778b/starfort-station-14 pull request #19
Opened 2023-04-09 11:19 UTC by MetalSage

closed #9

2023-04-09 11:20 UTC, fedKotikeD commented
уже есть #18

2023-04-09 12:35 UTC, MetalSage commented
Всё проверил, всё работает 👍🏿
![image](https://user-images.githubusercontent.com/74924875/230772764-4afdbb39-d5d2-4690-81ef-6893356a5800.png)

2023-04-09 12:39 UTC, MetalSage commented
Пофиксил перевод обычного внешнего шлюза

2023-04-09 12:45 UTC, fedKotikeD approved these changes
Мне все нравится

2023-04-09 16:55 UTC, 778b requested changes

2023-04-09 16:55 UTC, 778b commented on Resources/Prototypes/Palettes/departmental.yml
> +    expedition: "#00836E96"
бля я не тот цвет скинул, правильный #353b11

2023-04-09 16:55 UTC, 778b commented
бля и не надо все в один ПР хуячить, 1 ПР - 1 исуе

2023-04-10 06:30 UTC, MetalSage commented
No merged?
[c9be049f74125dbd924b30c46003910c.png](https://user-images.githubusercontent.com/74924875/230841351-1cee9f20-2404-4943-8f85-0986fbda727b.png)

2023-04-10 06:32 UTC, kzhanik commented
Жди фикс визардов бля

2023-04-10 07:21 UTC, 778b commented
> No merged? ![c9be049f74125dbd924b30c46003910c.png](https://user-images.githubusercontent.com/74924875/230841351-1cee9f20-2404-4943-8f85-0986fbda727b.png)

No kartinka with department color?

2023-04-10 11:38 UTC, MetalSage commented
> > No merged? ![c9be049f74125dbd924b30c46003910c.png](https://user-images.githubusercontent.com/74924875/230841351-1cee9f20-2404-4943-8f85-0986fbda727b.png)
> 
> No kartinka with department color?

![image](https://user-images.githubusercontent.com/74924875/230894581-49fc5730-8861-4ad9-bc3f-0be9f58db76b.png)
img with departament color

2023-04-10 12:18 UTC, 778b approved these changes

2023-04-10 15:48 UTC, merged