Add lockers
778b/starfort-station-14 pull request #22
Opened 2023-04-09 13:36 UTC by fedKotikeD

Добавляет шкафы. Поскольку я еще много не сделал будет драфтом. 
closes #12

2023-04-09 20:22 UTC, 778b requested changes
Понятное дело что у тебя драфт, но мне кажется лучше щас написать что я уже вижу чем потом. Ксати подумай про такие вещи как сканер узлов, аптечки, магбуты, медипены (их в игре больше 4)

2023-04-09 20:22 UTC, 778b commented on Resources/Prototypes/Catalog/Fills/Lockers/science.yml
Вообще правильней будет создать отдельный файл под ящики экспедиций, потому что в папке уже иерархия такая что каждый файл = отдел

2023-04-09 20:22 UTC, 778b commented on Resources/Prototypes/Catalog/Fills/Lockers/science.yml
> +  parent: LockerScientist
Наследоваться правильнее от LockerBaseSecure, потому что щас доступ у тебя только ученого, а если ты все это тут переопределишь и так то тогда наследование от готового ящика ученого вообще не имеет смысла.

2023-04-09 20:22 UTC, 778b commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> +      - id: Flash
вспышка, как и очки сб им не к чему, потому что это солдаты, а не полицейские. Так же шлем и бронежилет им не нужен тк они большую часть времени будут в скафандре, а по станции ходить в броне и шлеме по приколу - не логично

2023-04-09 20:54 UTC, 778b commented
+ я тебе спрайты добавил поэтому можешь их использовать

2023-04-10 05:09 UTC, fedKotikeD commented on Resources/Prototypes/Catalog/Fills/Lockers/science.yml
Да, так наверное будет проще

2023-04-10 05:10 UTC, fedKotikeD commented
> + я тебе спрайты добавил поэтому можешь их использовать

Спасибо. В течении дня все три неровности поправлю

2023-04-10 17:29 UTC, fedKotikeD commented on Resources/Prototypes/Catalog/Fills/Lockers/security.yml
> +      - id: Flash
Сделал

2023-04-10 17:29 UTC, fedKotikeD commented on Resources/Prototypes/Catalog/Fills/Lockers/science.yml
> +  parent: LockerScientist
Сделал

2023-04-10 17:29 UTC, fedKotikeD commented on Resources/Prototypes/Catalog/Fills/Lockers/science.yml
Сделал

2023-04-11 11:02 UTC, fedKotikeD commented on Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
> +  id: LockerExpeditionScience
Сделано

2023-04-11 11:02 UTC, fedKotikeD commented on Resources/Prototypes/Catalog/Fills/Lockers/expedition.yml
> +  parent: LockerBaseSecure
Сделано

2023-04-11 11:15 UTC, 778b requested changes
Ну все осталось поправить спрайты и сделать ящик медика и все гуд

2023-04-11 11:43 UTC, fedKotikeD commented on Resources/Prototypes/Entities/Structures/Storage/Closets/Lockers/lockers.yml
> +      state: fieldtroop
Поменял в [https://github.com/778b/starfort-station-14/pull/22/commits/1593a7007bab791ecd6a87a4cc6ebf12aeb119a8](этом коммите)

2023-04-11 11:55 UTC, 778b requested changes
Мне кажется финальные правки и готово. Перевод наверное тоже в отдельный файл и добавить перевод для мед шкафа

2023-04-11 11:55 UTC, 778b commented on Resources/Prototypes/Catalog/Fills/Lockers/expedition.yml
> +      - id: ClothingBeltMedical
Ты точно пустой хотел а не ClothingBeltMedicalFilled?

2023-04-11 11:55 UTC, 778b commented on Resources/Prototypes/Catalog/Fills/Lockers/expedition.yml
> +      - id: ClothingMaskSterile
им наверное лучше давать маску которая дыхабельная (к которой баллон можно подключить), ну или как вариант всем давать противогаз исследователя.

2023-04-11 11:55 UTC, 778b commented on Resources/Prototypes/Catalog/Fills/Lockers/expedition.yml
> +    contents:
Газовой маски нет, противогаз исследователя будет в вендомате поэтому думаю лучше его добавить, ну и магазины для лектора добавить на первое время

2023-04-11 17:51 UTC, fedKotikeD commented on Resources/Prototypes/Catalog/Fills/Lockers/expedition.yml
> +      - id: ClothingBeltMedical
ну это было скопировано с шкафа врача

2023-04-11 18:59 UTC, 778b approved these changes

2023-04-11 18:59 UTC, merged